node_js:
- '6'
- '7'
- '8'
sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: npm run test
# after_script: npm i -g codecov.io && cat ./coverage/lcov.info | codecov
